### ISSUE TITLE
Issues with Working With Ballerina Modules page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#1605] opened 2020-12-18 07:02 UTC
**Description:**
Noticed below issues with the page `Working With Ballerina Modules` [1]

1. Breadcrumb topic is displayed partially

<img width="758" alt="image" src="https://user-images.githubusercontent.com/16300038/102584604-c71f0f00-412c-11eb-919a-bf4162294ac3.png">

2. Page is not displayed in left navigation panel. Since it is an important topic we need to add it there as a sub topic. Currently link is available only via the last section of [2]

[1] https://ballerina.io/swan-lake/learn/structuring-ballerina-code/working-with-ballerina-modules/
[2] https://ballerina.io/swan-lake/learn/structuring-ballerina-code/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment] 2020-12-18 10:53
Closing since this issue is a duplicate of [1] and [2].

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/1526
[2] https://github.com/ballerina-platform/ballerina-dev-website/issues/1522

**Closed by praneesha** 2020-12-18 10:53 UTC
Labels: Type/Improvement
