### ISSUE TITLE
Broken link in `Code to Cloud Deployment` page

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-dev-website#3650] opened 2022-01-30 10:07 UTC
**Description:**

In the following page (http://dev.ballerina.io/learn/running-ballerina-programs-in-the-cloud/code-to-cloud-deployment/)

if we navigate to the `Running ballerina programs in the cloud` link, 

It will direct to (http://0.0.0.0:4000/learn/running-ballerina-programs-in-the-cloud/code-to-cloud-deployment/)

![Screenshot from 2022-01-30 15-35-07](https://user-images.githubusercontent.com/31839712/151695271-a1680785-4f96-48c7-8d41-31289a7faeba.png)

**Comment by praneesha** [comment] 2022-01-30 11:37
Closing since this is a duplicate of [1].

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/3605

**Closed by praneesha** 2022-01-30 11:37 UTC
Labels: Priority/Highest, Area/Backend, Type/Bug, Area/LearnPages
