### ISSUE TITLE
Remove % signs on the URLs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4896] opened 2022-07-27 08:35 UTC
## Description
It is better if we can remove the % signs that appear in the URLs and replace them with dashes instead as done in [1].

<img width="986" alt="Screenshot 2022-07-27 at 14 04 44" src="https://user-images.githubusercontent.com/11707273/181201339-7cc35ba3-e7b0-4524-ac70-508b0761de2c.png">

[1] https://wso2.com/choreo/docs/scheduled-tasks/#deploy-a-scheduled-task

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment] 2022-07-27 11:43
Closing as this is a duplicate of #4741

**Closed by sm1990** 2022-07-27 11:43 UTC
Labels: Type/Task, Area/LearnPages, WebsiteRewrite
