### ISSUE TITLE
SwanLake BBE - Copy to clipboard button issue

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#1104] opened 2020-07-23 16:43 UTC
**Description:**
In Swan lake version of BBEs , when we click on copy to clip board button it copies output text as well. (Not only the source code)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamil321** [comment] 2020-08-11 06:10
Adding more to the issue, this behavior is seen only for the swan-lake

**Comment by praneesha** [comment] 2020-09-02 09:19
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/288.

**Closed by praneesha** 2020-09-02 09:19 UTC
Labels: Priority/High, Type/Docs, bug
