### ISSUE TITLE
Broken Header and footer sections in 404 page

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4871] opened 2022-07-27 04:39 UTC
## Description
As shown below,

1. Header section is missing.
2. Footer section is having incorrect styling + arrangements.
3. Styling of the hyperlinks (`go back`, `report your issue` and `Ballerina Team`) are different from the other pages.

<img width="1436" alt="Screenshot 2022-07-27 at 10 04 22" src="https://user-images.githubusercontent.com/29032600/181162277-ee58d119-2a26-4594-b723-48224d566a87.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment] 2022-07-27 09:48
Unable to reproduce.

**Comment by sm1990** [comment] 2022-07-27 18:25
Closing as invalid

**Closed by sm1990** 2022-07-27 18:25 UTC
Labels: Type/Bug, Reason/Invalid, WebsiteRewrite
