### ISSUE TITLE
Update the Dark/Light Theme Based on the User Color Scheme

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-dev-website#9060] opened 2024-06-07 04:09 UTC
## Description

The Ballerina Central now supports the dark theme, which looks great IMO. 

Ideally, the dark theme should be enabled when the user is using dark theme in his machine. Otherwise, the dark theme has o be selected each time we visi.t (Not each time, but you get the idea).

**Comment by anupama-pathirage** [comment] 2024-08-22 18:29
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/3120

**Closed by anupama-pathirage** 2024-08-22 18:29 UTC
Labels: Category/UIUX, Type/Improvement, Area/WebsiteCommon

**Comment by ThisaruGuruge** [comment] 2024-08-23 07:11
The mentioned issue is to track dark theme on Ballerina website. This issue was about the Ballerina central, which has a dark theme. The idea of this is to apply the theme from the users' system theme, instead of taking manual input. (We can keep the button to select theme manually, but the default theme should be picked from the user settings).
