### ISSUE TITLE
rabbitmq_consumer.bal copy clip board option copies invalid source

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-dev-website#274] opened 2019-12-19 07:29 UTC
**Description:**
$title, when pasted, added a block comment at the end of the source giving compilation errors

**Steps to reproduce:**
Copy to clip board and paste it on the editor

**Affected Versions:**
v1.1.0-alpha at least

**Comment by praneesha** [comment] 2020-09-02 09:25
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/288.

**Closed by praneesha** 2020-09-02 09:25 UTC
