### ISSUE TITLE
Broken Links in Archived versions page

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#4496] opened 2022-06-03 06:22 UTC
## Description
`RELEASE NOTES` links are not working from 1.1.4 onward in [1]

[1] https://ballerina.io/downloads/1.2.x-archived/#1.1.4

**Comment by praneesha** [comment] 2022-06-24 15:24
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/3440.

**Closed by praneesha** 2022-06-24 15:24 UTC
Labels: Area/UIUX, Type/Bug
