### ISSUE TITLE
In the 1.2.x site, the Ballerina ZIP download link points to the staging bucket

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#3241] opened 2021-12-11 07:17 UTC
https://ballerina.io/1.2/learn/installing-ballerina/#installing-via-the-ballerina-language-zip-file

**Comment by praneesha** [comment] 2021-12-22 11:30
Closing since this is a duplicate of #3289

**Comment by pubudu91** [comment] 2021-12-22 14:38
> Closing since this is a duplicate of #3289

This is not a duplicate of it. This issue is about the zip download link pointing to the staging S3 bucket instead of the prod S3 bucket.

**Comment by praneesha** [comment] 2021-12-22 14:58
> > Closing since this is a duplicate of #3289
> 
> This is not a duplicate of it. This issue is about the zip download link pointing to the staging S3 bucket instead of the prod S3 bucket.

Since the links were changed to liquid syntax in #3289 pointing to the prod S3 bucket will also be handled by it. Anyway, will double-check and close.

**Comment by praneesha** [comment] 2021-12-23 03:55
Closing since the links are fixed in [1] now.

[1] https://ballerina.io/1.2/learn/installing-ballerina/#installing-via-the-ballerina-language-zip-file

**Closed by praneesha** 2021-12-23 03:55 UTC
Labels: Priority/High, Area/Docs, Type/Bug
