### ISSUE TITLE
Less details on where to place the external java class in Ballerina FFI

### ISSUE THREAD

**Issue by Dil-G** [ballerina-platform/ballerina-dev-website#4231] opened 2022-04-21 02:33 UTC
## Description
 In the Documentation, it is not given where to place the user defined external java class when calling the foreign code. Gives an error when defining the path of the java class from the source.

## Related website/documentation area

Area/ JAVA INTEROPERABILITY/ BALLERINA FFI

**Comment by IrushiL** [comment] 2022-04-25 00:54
@Dil-G Can you please elaborate on the issue or provide the steps to reproduce it?

You need to point to a JAR file when calling an external Java library. From what you mentioned in the description it looks like you were trying to point to a Java class, which is not the way for adding dependencies. The section on providing platform dependencies is given here in [Package References](https://ballerina.io/learn/package-references/#platform-dependencies) and it is pointed as a reference in the [Calling Java code from Ballerina](https://ballerina.io/learn/call-java-code-from-ballerina/#write-ballerina-bindings) guide as well. Can you please point out exactly what is missing in this documentation in your opinion?

**Comment by praneesha** [comment] 2022-05-06 04:38
Closing as per the above reply. @Dil-G - Please reopen if any further improvements can be suggested.

**Closed by praneesha** 2022-05-06 04:38 UTC
Labels: Type/Improvement, Area/LearnPages
