### ISSUE TITLE
Backticks are not getting rendered inside right hand side ToC

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4898] opened 2022-07-27 08:45 UTC
## Description
$subject. Is this intentional?

## Dev
<img width="238" alt="Screenshot 2022-07-27 at 14 12 15" src="https://user-images.githubusercontent.com/29032600/181203577-0bb4e1ca-eb36-4343-af4d-9279fd632cac.png">

## Prod
![Screenshot 2022-07-27 at 14 12 05](https://user-images.githubusercontent.com/29032600/181203623-443ec672-c140-4b24-a7d7-b28d81c6743e.png)

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment] 2022-07-27 11:56
Closing as this is a duplicate of #4785

**Closed by sm1990** 2022-07-27 11:56 UTC
Labels: Type/Bug, WebsiteRewrite
