### ISSUE TITLE
Navigation bar resets when a new link is opened in learn by example page

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-dev-website#2743] opened 2021-08-24 05:05 UTC
**Description:**

Currently navigated to
<img width="1792" alt="Screenshot 2021-08-24 at 10 32 53" src="https://user-images.githubusercontent.com/15815199/130558659-bc9c925c-bb8c-44be-b239-52a1d5bf576e.png">

Thereafter I go to the next page
<img width="1792" alt="Screenshot 2021-08-24 at 10 34 06" src="https://user-images.githubusercontent.com/15815199/130558762-9f251c74-9326-4a86-bdd8-1aab430abbcd.png">

Note the navigation bar.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment] 2021-08-30 05:22
2/Points

**Comment by praneesha** [comment] 2021-09-22 07:58
Closing since this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/2844.

**Closed by praneesha** 2021-09-22 07:58 UTC
Labels: Priority/Highest, Area/UI, Type/Bug, Points/2
