### ISSUE TITLE
The calling java code from ballerina and vice versal page is too long.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2868] opened 2021-09-27 20:01 UTC
**Description:**
$subject in [1]. Break properly.

[1] https://ballerina.io/learn/calling-java-code-from-ballerina-and-vice-versa/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment] 2021-09-28 11:12
Closing since this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/606.

**Closed by praneesha** 2021-09-28 11:12 UTC
Labels: Type/Improvement
